### ISSUE TITLE
Support metadata argument for policy assignments

### ISSUE THREAD

**Issue by timwebster9** [gettek/terraform-azurerm-policy-as-code#31]
# Issue Template

## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

* Module Version: 2.60
* Terraform Version: 1.2.3
* AzureRM Provider Version: 3.10.0

## Expected Behavior
The def_assignment should be able to set the 'metadata' field on a policy assignment

## Current Behavior
There is no variable for metadata, so it doesn't get set.

Some context: In our situation, we are planning on adding logic to policy rules to cover waiver scenarios instead of using exemptions (e.g. for stuff where the entire estate will be affected, like allowing direct routes to Azure control plane destinations).  In these cases, we would like to track the waiver metadata in the policy assignment since we won't be using exemptions.  Putting the metadata in the policy definition is also an option, but assignment should support it as well.

**Comment by gettek** [comment]
I've not included that argument due to the auto generated meta handled by the curent AzureRM provider on assignments, please refer to [this issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/14380).

Until `systemData` becomes available under the newer API versions, it will be difficult to prevent inconsistent plan/apply as there is no way to `ignore_lifecycle` of specific metadata i.e. `["assignedBy", "createdBy", "createdOn", "updatedBy", "updatedOn"]`.

Last time I tried implementing this feature all assignments would be updated on apply but I recommend running some tests, adding metadata manually on assignment and feedback here.
