### ISSUE TITLE
Assignments with remediation Applied - Timestamp

### ISSUE THREAD

**Issue by Adam-McGill** [gettek/terraform-azurerm-policy-as-code#65]
Hi @gettek ,

I would like to know if the behavior for remediation tasks in the module set_assignment is intended with naming the resource with a timestamp?  As running a plan/apply will see the resources as net new each time it is applied.  Wanting to destroying the existing with older time stamp and replaced with newer one / new timestamp.  Thanks for your time, great job on the module/repo.

**Comment by gettek** [comment]
Hi @Adam-McGill, yes this is intentional.

Say for example you have a scheduled nightly build of your policy pipeline, this behaviour attempts to ensure continuous compliance by shifting responsibility on the Azure Policy Engine to remediate non-compliant resources.

Specifying `skip_remediation=true` will prevent creation of new tasks: [See Here](https://github.com/gettek/terraform-azurerm-policy-as-code#remediation-tasks)

**Comment by Adam-McGill** [comment]
This answered my question and can close. Thanks
